//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TARpe23_XML_Donnet
{


    public partial class Parameeter
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Xml xml1;
        protected global::System.Web.UI.WebControls.TextBox kast1;
        protected global::System.Web.UI.WebControls.TextBox kast2;
        protected global::System.Web.UI.WebControls.TextBox kast3;
        protected global::System.Web.UI.WebControls.TextBox kast4;
        protected global::System.Web.UI.WebControls.TextBox kast5;
        protected global::System.Web.UI.WebControls.Button btnSisesta;

    }
}
